### ISSUE TITLE
no data out from ublox M8P when using UbxGpsNavPvt

### ISSUE THREAD

**Issue by rikaad** [loginov-rocks/UbxGps#11]
Hi,
I am using a u-blox M8N receiver connected to an Arduino Mega as indicated in the instructions. The auto-configuration-mega sketch works fine (i assume) and results in binary data appearing on the arduino console. However when i upload and use the UbxGpsNavPvt sketch i get no output  - i assume this is because it cant find the correct UbxGps_Header values. Could this in turn be due to the Ublox8 in 0x01 0x07 Nav-Pvt message having 92 bytes instead of 84. If this is the case, how would i fix this.

Any help is much appreciated.

**Comment by loginov-rocks** [comment]
Hi @rikaad !

You can create your own class extending https://github.com/1oginov/UbxGps/blob/master/src/UbxGpsNavPvt.h with structure you have for U-blox 8. Data structure should match the message structure (byte/short/long/etc).

Same as #10
