### ISSUE TITLE
Serial.available() everytime only 4 Bytes

### ISSUE THREAD

**Issue by Olgidos** [loginov-rocks/UbxGps#14]
I am using an UBlOX M8U with Serial and want ot get the PVT information.
I am trying around with your library but get no results.
When ich just use a Scetch to out print all bytes that reach my arduino, i get the orignal message like in U-center.
The problem is, these bytes come always as 4. so Serial.available will alwas go out of the while scope after 4 bytes ?!?.
So its not possible to get a complete message over the library
andy advice?

**Comment by loginov-rocks** [comment]
Hi @Olgidos !

Check docs if the PVT message of yours M8U is the same as in the UbxGpsNavPvt.h - probably there is some difference.
