### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by RossMelbourne** [loginov-rocks/UbxGps#15]

**Comment by RossMelbourne** [comment]
I am very new to uBlox and GPS so please excuse the basic questions. I see your code can be compiled in Visual Studio.  Could it be adapted to run on a Windows PC using the USB/Serial port?  If so, what would need to change please?

**Comment by loginov-rocks** [comment]
Hello @RossMelbourne !

This library was developed on a Windows machine actually, so nothing special needed :)

**Comment by loginov-rocks** [comment]
@RossMelbourne please describe the difficulties you have encountered, then we can reopen the issue.

**Comment by RossMelbourne** [comment]
I guess I need a 'Quick start' document for running this in Visual Studio on a Windows PC.

**Comment by loginov-rocks** [comment]
https://github.com/1oginov/UbxGps#quick-start

**Comment by RossMelbourne** [comment]
That appears to me to be a Quick start for Arduino rather than for a Windows PC.  Sorry for not making my intentions clearer.  I want to be able to attach the u-Blox GPS to the USB port on a Windows PC and run your code via Visual Studio.  I used to develop in VS but it was a very long time ago so now I am a bit lost :-)

**Comment by loginov-rocks** [comment]
Oh! I guess I know what's missing, https://platformio.org/ - it's an extension for Visual Studio _Code_ to compile C/C++ sources and upload them to the Arduino.

Talking about communication between u-blox and Windows PC, you don't need this library to start. Just a UART-USB converter (Arduino can be used for this as a serial bridge https://github.com/1oginov/UbxGps#step-2-serial-bridge). After you get u-blox working, you can configure it as described in the readme and move further with testing this library.
