### ISSUE TITLE
Library doesn't appear to work with the u-blox m8q

### ISSUE THREAD

**Issue by mikcatta** [loginov-rocks/UbxGps#16]
Hi

I am trying to find a library that will work with the ublox M8Q module and this one looked promising. I have followed the instructions and u-center shows a 3D fix using the Serial-Bridge-Mega app. However, the example app doesn't seem to like the NAVPvt data from this module as it never resolves the gps.ready() function to true.

I am testing this with a Seediono Mega 2560, with the GPS hooked upto serial port 3 (pins 14&15). The GPS is defined as follows :- UbxGpsNavPvt<HardwareSerial> gps(Serial3);

I have also tried softwareserial on the Moteino, but that didn't want to play either.

I don't know enough about the binary protocol to dig any deeper. Any thing else I can try?

**Comment by loginov-rocks** [comment]
Hello, @mikcatta !

Please take a look at #10 and #11
