### ISSUE TITLE
How do I use 2 (or more) messages in the same sketch?

### ISSUE THREAD

**Issue by unocerobits** [loginov-rocks/UbxGps#2]
Following your code, would be possible to receive PVT and POS messages in the same sketch?
Thanks

**Comment by loginov-rocks** [comment]
@unocerobits unfortunately no.

The main idea of this library is to get the minimum required data set in the shortest possible time, we do not want to care what type of message is sent from the receiver, so it should be configured to send one type message only. So in your sketch you use specified class to get it, UbxGpsNavPvt for example, or UbxGpsNavPosllh, etc.

What kind of data do you need? We can check [protocol specification](https://github.com/1oginov/UBX-GPS-Library/raw/master/Docs/u-blox%207%20Receiver%20Description%20Including%20Protocol%20Specification%20V14.pdf) to find message type suiting your aims and implement it in library.

**Comment by unocerobits** [comment]
Thanks for your answer,
Would be great that your library can to work with anothers messages simultaneosly, I think that the problem can be to unify serial handler in `UbxGps.h` header instead on the each message header ( I agree with you in your  faster method). 

I'm working in this with `ODO `and `HNR-PVT`, this are exclusive messages from UDR model NEO-M8U. When I work with each one alone works great, but I have problems when I try to work with both simultaneously (Obviously modifying your sources).

I thought that you had (maybe) thought a solution or alternative.
Thanks for your time!
