### ISSUE TITLE
u-blox neo-m9n

### ISSUE THREAD

**Issue by tcpipchip** [loginov-rocks/UbxGps#20]
Sir, i am support to smartcore, a u-blox representative and i am doing a blog about the NEO-M9N. 

The blog going well, gathering info to help the client.

Looking the internet i found your UBXm protocol. Will it works to NEO-M9N ? I see that NEO-M9N implements too UBX protocol.

If yes, i will test and add your GITHUB to it.

Thank you!

**Comment by loginov-rocks** [comment]
Hi @tcpipchip ,

I still didn't get the chance to test with other modules, so if this already tested and works please ping me so I'll add it to the description. Thanks and sorry for such a long answer (shame on me) :(

**Comment by tcpipchip** [comment]
no problem! I will tranform your GITHUB in a blog! ok ?

**Comment by loginov-rocks** [comment]
> no problem! I will tranform your GITHUB in a blog! ok ?

Hi @tcpipchip ,

Sorry, not sure what you meant :) If you want to use any information from this repository - feel free, as it's MIT licensed :)

**Comment by tcpipchip** [comment]
I published your LIB reference in our BLOG
https://u-blox-zed-f9p.blogspot.com/2021/04/ubxgps-esta-biblioteca-arduino-foi.html

**Comment by loginov-rocks** [comment]
That's nice, thank you @tcpipchip !

**Comment by tcpipchip** [comment]
welcome
