### ISSUE TITLE
Settings Gps module function

### ISSUE THREAD

**Issue by maxtwin048** [loginov-rocks/UbxGps#21]
hello, is it possible to adjust the navigation update speed of 5-10khz, and change the boudrate from 9600 to 115200 via arduino sketch?

**Comment by loginov-rocks** [comment]
> hello, is it possible to adjust the navigation update speed of 5-10khz, and change the boudrate from 9600 to 115200 via arduino sketch?

Hi @maxtwin048 ,

Yes, it's possible the same way as in the Configuration sketch:
- changeBaudrate https://github.com/loginov-rocks/UbxGps/blob/master/extras/Configuration/Auto-configuration-Mega/Auto-configuration-Mega.ino#L211
- changeFrequency https://github.com/loginov-rocks/UbxGps/blob/master/extras/Configuration/Auto-configuration-Mega/Auto-configuration-Mega.ino#L250

So if you'd like to have other values, you need to build another payload for those packets. You can find more information about the configuration packets in the ublox Protocol Spec or just check what u-center sends when changing those values in the app.
