### ISSUE TITLE
NEO-6M0 GPS

### ISSUE THREAD

**Issue by skatun** [loginov-rocks/UbxGps#24]
Your library works on the NEO-6M0 gps, however its not possible to enable the UbxGpsNavPvt in Ucenter, other messages works fine. For me that's ok since I do not need course information

**Comment by loginov-rocks** [comment]
Hi @skatun , thanks for feedback! Do you know if NEO-6M0 have this message type in their protocol? It could be they just don't support it...

**Comment by skatun** [comment]
https://content.u-blox.com/sites/default/files/products/documents/u-blox6_ReceiverDescrProtSpec_%28GPS.G6-SW-10018%29_Public.pdf

you might be right!

Is there a spesfic reason why you can only read one type of message at time? It would be nice to get information about GPS fix, and satelites at startup and ones in a while...

**Comment by loginov-rocks** [comment]
@skatun  yes, I created this to make communication as fast as possible, so choosing only one type of message is essential. The key is to select the message that has enough information for your needs and get it as many times as possible, that was 10 Hz in my case :)
