### ISSUE TITLE
Is it possible to use for Particle Electron/Photon

### ISSUE THREAD

**Issue by mnelson920** [loginov-rocks/UbxGps#3]
Hi @1oginov,

Is it possible to use this library with Particle Electron/Photon?

Thanks

**Comment by loginov-rocks** [comment]
Hi, @mnelson920!

Depends on what microcontrollers are used in the _Particle Electron/Photon_, of course. If it supports C++, then probably yes.

The library is just a bunch of C++ source, but it consumes an instance of `Serial`, that is implemented in Arduino basic library. So if you want to plug'n'play the library, but _Particle Electron/Photon_ are not built on top of Arduino, then you have to do some work.
