### ISSUE TITLE
problem while compile

### ISSUE THREAD

**Issue by santersa** [loginov-rocks/UbxGps#6]
I receive an error message while compiling the test sketch on string #18
UbxGpsNavPvt gps(Serial3);

here is message
UbxGpsNavPvt:18: error: 'Serial3' was not declared in this scope

 UbxGpsNavPvt gps(Serial3);
                               ^

exit status 1
'Serial3' was not declared in this scope

What i have to write there?

**Comment by loginov-rocks** [comment]
Hi @santersa 

The error explains that you have not `Serial3`, type in the serial you have. What board are you using?

**Comment by phdaerospace** [comment]
I too got the same error. I am using Arduino Nano.

**Comment by loginov-rocks** [comment]
Hi @phdaerospace 

Nano board has only one `Serial`, so take a look at **Uno** sketches and how-to.
