### ISSUE TITLE
Missing 'Graphic' for GPS status info

### ISSUE THREAD

**Issue by AussieMakerGeek** [loginov-rocks/UbxGps#8]
Hi, in the source, it mentions 'Graphic Below' - Where are these graphics?
`char            valid;      // -        Validity Flags (see graphic below)`
`char            flags;      // -        Fix Status Flags (see graphic below)`

I would really like the ability to know if the GPS has a fix or not i.e valid GPS data.  This seems like it might be the option I am looking for...

**Comment by loginov-rocks** [comment]
Hi @ahuxtable !

These comments are taken from protocol specification, so you can follow [extras/Docs](https://github.com/1oginov/UbxGps/tree/master/extras/Docs) or find suitable specification on the web, search for the appropriate packet and go to its description.

For this case I personally use `fixType` for `UbxGpsNavPvt.h`
